### ISSUE TITLE
Why require a Jurisdiction for each Event?

### ISSUE THREAD

**Issue by gordonje** [opencivicdata/python-opencivicdata-django#79]
The `Event` Django model currently has a `jurisdiction` foreign key field with a not null constraint. However, this field is not mentioned in the [OCD Event format](http://opencivicdata.readthedocs.io/en/latest/data/event.html) or in the [Event OCDEP](http://opencivicdata.readthedocs.io/en/latest/proposals/0004.html).

Assuming the typical use case is to model meetings of various public agencies (e.g., a state legislative committee or city council), couldn't that be handled via an `Organization` as an event participant?

**Comment by jamesturk** [comment]
I think the main reason is for scoping Events & deduplication.  At present, I believe everyone using these models have a single DB that is multi-jurisdiction- as such there needs to be an easy way to separate Jurisdiction's organizations/etc.

https://github.com/opencivicdata/pupa/blob/master/pupa/importers/events.py#L40 is an example of where this is done, we consider the unique set of attributes for an Event to be {name,description,start,end,timezone,jurisdiction}

& because participants aren't stored on the Event object we can't easily use them like this

(for a single-jurisdiction instance Jurisdiction is likely to be an implementation detail that can be essentially ignored)

**Comment by fgregg** [comment]
How about having an `Event` class without this attribute, and then having a `LegislativeEvent` subclass with this attribute that pupa would use?

**Comment by jamesturk** [comment]
Would we do that for all models that depend on Jurisdiction?

**Comment by fgregg** [comment]
I don't think I understand your question. The `LegislativeEvent` would be the exact same thing as the current `Event`. The new `Event` would be compliant with the OCD spec and ready to be used for non pupa purposes.

**Comment by jamesturk** [comment]
Would we want do the same for Organization/etc?

**Comment by jamesturk** [comment]
Also, I think we should choose a better name that Legislative* if we do
this, there's nothing specifically Legislative about needing a Jurisdiction

**Comment by fgregg** [comment]
Hmm.. interesting.  Political campaigns don't really have jurisdictions and we are going to want to model those.  I can't think of a governmental organization that doesn't have a jurisdiction. 

I think we will need to have a conversation of jurisdiction-less organizations, but that should probably happen on https://github.com/opencivicdata/docs.opencivicdata.org/, since the current OCD spec does require jurisdictions.

In any case, as you have said, the case for `Events` is different. We are not saying that `Events` truly have or are associated with jurisdictions, but we have used jurisdictions as convenient scoping mechanism.

**Comment by jamesturk** [comment]
FWIW, I feel like Event missing Jurisdiction on docs.opencivicdata.org was an accident, not an intentional choice.  If you had an Event that wasn't tied to a Jurisdiction how would you deduplicate it?

**Comment by fgregg** [comment]
Well, the spec is the spec. We should go through OCDEP process either way.

Right now pupa uses name, description, start_time, end_time, timezone, and jurisdiction_id. I think if you added location and removed jurisdiction, you would have something just as deduplicable.

**Comment by jamesturk** [comment]
location makes sense, forgot that was already required.  I'd be open to an
OCDEP

It'll be trickier to implement because it isn't a key on the top level
object, but should be doable if someone is up for tackling it.

**Comment by gordonje** [comment]
Conversation has moved [here](https://github.com/opencivicdata/docs.opencivicdata.org/issues/84).
